### ISSUE TITLE
Is there a reason, why rtabmap_ros does not have debian package apt? 

### ISSUE THREAD

**Issue by hodnajit** [introlab/rtabmap_ros-release#1]
Hi,

I like you project, I tried to install it on rolling and I have a question, if there is a reason, why you do not publish rolling apt packages for rtabmap_ros?

Thanks

Best regards Jitka

**Comment by matlabbe** [comment]
It depends on Nav2 package, which ia not released onrolling since a compatibility issue with ubuntu 22.04. We would need to make nav2 dependency optional in the package.xml, just for rolling, not sure if it is possible.

**Comment by hodnajit** [comment]
Oh, that make sense. Thanks.
